backend:
  name: github
  repo: courtneyring/crawford-county-historical-society
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "home" # Used in routes, e.g., /admin/collections/blog
    label: "Home" # Used in the UI
    folder: "src/copy/home" # The path to the folder where the documents are stored
    slug: "copy" # Filename template, e.g., YYYY-MM-DD-title.md
    summary: 'CCHS Home Copy'
    fields: # The fields for each document, usually in front matter
      - label: "Hero"
        name: "hero"
        widget: "object"
        summary: "{{fields.title}}"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
      - { label: 'Intro', name: 'intro', widget: 'text'}
      - label: "Image Promos"
        name: "imagePromos"
        widget: "list"
        allow_add: true
        summary: "{{fields.header}} - {{fields.body}}"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Header", name: "header", widget: "text" }
          - { label: "Body", name: "body", widget: "text" }
          - label: "CTA"
            name: "cta"
            widget: "object"
            fields: 
              - {label: Label, name: label, widget: string}
              - {label: Value, name: value, widget: string}
  - name: "navigation"
    label: "Navigation"
    summary: "CCHS Navigation Copy"
    create: true
    folder: "src/copy/navigation"
    slug: "copy"
    fields: 
      - {label: "Title", name: "title", widget: "string", required: false }
      - {label: "Image", name: "image", widget: "image", required: false }
      - label: "Links"
        name: "links"
        summary: "{{fields.label}} - {{fields.value}}"
        widget: "list"
        allow_add: true
        fields:
          - {label: Label, name: label, widget: string}
          - {label: Value, name: value, widget: string}
  - name: "footer"
    label: "Footer"
    summary: "CCHS Footer Copy"
    folder: "src/copy/footer"
    slug: "footer"
    fields: 
      - {label: "Logo", name: "logoImg", widget: "image"}
      - label: "Hours"
        name: "hours"
        widget: "list"
        allow_add: true
        fields: 
          - {label: "Label", name: "label", widget: "string"}
          - {label: "Value", name: "value", widget: "string"}
      - label: "Links"
        name: "links"
        summary: "{{fields.label}} - {{fields.value}}"
        widget: "list"
        allow_add: true
        fields:
          - {label: Label, name: label, widget: string}
          - {label: Value, name: value, widget: string}
      - label: 'Address'
        name: 'address'
        widget: object
        fields: 
          - label: 'Street'
            name: 'street'
            widget: string
          - label: 'PO Box, Suite, etc'
            name: 'street2'
            widget: string
          - label: 'City'
            name: 'city'
            widget: string
          - label: 'State'
            name: 'state'
            widget: string
          - label: 'Zip Code'
            name: 'zip'
            widget: number
  - name: "about"
    label: "About"
    summary: "CCHS About Copy"
    folder: "src/copy/about"
    slug: "copy"
    fields: 
      - label: "HeroImage"
        name: "heroImage"
        widget: "image"
      - label: 'Page Title'
        name: 'pageTitle'
        widget: string
      - label: 'Body'
        name: 'body'
        widget: text
  - name: "gallery"
    label: "Gallery"
    summary: "CCHS Gallery Copy"
    folder: "src/copy/gallery"
    slug: "copy"
    fields: 
      - label: "HeroImage"
        name: "heroImage"
        widget: "image"
      - label: 'Page Title'
        name: 'pageTitle'
        widget: string
      - label: 'Images'
        name: 'images'
        widget: list
        allow_add: true
        fields: 
          - {label: Image, name: image, widget: image}
  - name: "support"
    label: "Support"
    summary: "CCHS Support Copy"
    folder: "src/copy/support"
    slug: "copy"
    fields: 
      - label: "HeroImage"
        name: "heroImage"
        widget: "image"
      - label: 'Page Title'
        name: 'pageTitle'
        widget: string
  - name: "board"
    label: "Board"
    summary: "CCHS Board Copy"
    folder: "src/copy/board"
    slug: "copy"
    fields: 
      - label: "HeroImage"
        name: "heroImage"
        widget: "image"
      - label: 'Page Title'
        name: 'pageTitle'
        widget: string
      - label: 'Members'
        name: 'members'
        widget: list
        allow_add: true
        fields: 
          - {label: Position, name: position, widget: string}
          - {label: Name, name: name, widget: string}
      - label: 'Attend'
        name: 'attend'
        widget: object
        fields: 
          - {label: Heading, name: heading, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Image, name: image, widget: image}
      - label: 'Contact'
        name: 'contact'
        widget: object
        fields: 
          - {label: Heading, name: heading, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Image, name: image, widget: image}
          - label: Cta
            name: cta
            widget: object
            fields: 
              - {label: Label, name: label, widget: string}
              - {label: Value, name: value, widget: string}
  - name: 'events'
    label: "Events"
    summary: "CCHS Events Copy"
    folder: 'src/copy/events'
    slub: 'copy'
    fields: 
    - label: "HeroImage"
      name: "heroImage"
      widget: "image"
    - label: 'Page Title'
      name: 'pageTitle'
      widget: string
    - label: Not Found Text
      name: notFoundText
      widget: string
    - label: 'Events'
      name: 'events'
      widget: 'list'
      allow_add: true
      fields: 
        - {label: Event Name, name: name, widget: string}
        - {label: Start, name: start, widget: datetime, date_format: "dddd, MMM D, h:mm a"}
        - {label: End, name: end, widget: datetime, date_format: "h:mm a"}
        - {label: Location, name: location, widget: string}
        - {label: Description, name: description, widget: text}
        - {label: Image, name: image, widget: image }
  - name: "contact"
    label: "Contact"
    summary: "CCHS Contact Copy"
    folder: "src/copy/contact"
    slug: "copy"
    fields: 
      - label: "HeroImage"
        name: "heroImage"
        widget: "image"
      - label: 'Page Title'
        name: 'pageTitle'
        widget: string
      - label: 'Address'
        name: 'address'
        widget: object
        fields: 
          - label: 'Street'
            name: 'street'
            widget: string
          - label: 'PO Box, Suite, etc'
            name: 'street2'
            widget: string
          - label: 'City'
            name: 'city'
            widget: string
          - label: 'State'
            name: 'state'
            widget: string
          - label: 'Zip Code'
            name: 'zip'
            widget: number
      - label: 'Phone'
        name: 'phone'
        widget: string
      - label: 'Email'
        name: 'email'
        widget: string
      - label: 'Hours'
        name: 'hours'
        widget: object
        fields: 
          - {label: 'Tuesday', name: 'tuesday', widget: string}
          - {label: 'Wednesday', name: 'wednesday', widget: string}
          - {label: 'Thursday', name: 'thursday', widget: string}
          - {label: 'Friday', name: 'friday', widget: string}
          - {label: 'Saturday', name: 'saturday', widget: string}
          - {label: 'Sunday', name: 'sunday', widget: string}
          - {label: 'Monday', name: 'monday', widget: string}