backend:
  name: github
  repo: courtneyring/crawford-county-historical-society
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "home" # Used in routes, e.g., /admin/collections/blog
    label: "Home" # Used in the UI
    folder: "src/copy/home" # The path to the folder where the documents are stored
    slug: "copy" # Filename template, e.g., YYYY-MM-DD-title.md
    summary: 'CCHS Home Copy'
    fields: # The fields for each document, usually in front matter
      - label: "Hero"
        name: "hero"
        widget: "object"
        summary: "{{fields.title}}"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
      - { label: 'Intro', name: 'intro', widget: 'text'}
      - label: "Image Promos"
        name: "imagePromos"
        widget: "list"
        allow_add: true
        summary: "{{fields.header}} - {{fields.body}}"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Header", name: "header", widget: "text" }
          - { label: "Body", name: "body", widget: "text" }
          - label: "CTA"
            name: "cta"
            widget: "object"
            fields: 
              - {label: Label, name: label, widget: string}
              - {label: Url, name: url, widget: string}
  - name: "navigation"
    label: "Navigation"
    summary: "CCHS Navigation Copy"
    create: true
    folder: "src/copy/navigation"
    slug: "copy"
    fields: 
      - {label: "Title", name: "title", widget: "string", required: false }
      - {label: "Image", name: "image", widget: "image", required: false }
      - label: "Links"
        name: "links"
        summary: "{{fields.label}} - {{fields.value}}"
        widget: "list"
        allow_add: true
        fields:
          - {label: Label, name: label, widget: string}
          - {label: Value, name: value, widget: string}
  - name: "about"
    label: "About"
    summary: "CCHS About Copy"
    folder: "src/copy/about"
    slug: "copy"
    fields: 
      - label: "HeroImage"
        name: "heroImage"
        widget: "image"
      - label: 'Page Title'
        name: 'pageTitle'
        widget: string
      - label: 'Body'
        name: 'body'
        widget: text
  - name: "gallery"
    label: "Gallery"
    summary: "CCHS Gallery Copy"
    folder: "src/copy/gallery"
    slug: "copy"
    fields: 
      - label: "HeroImage"
        name: "heroImage"
        widget: "image"
      - label: 'Page Title'
        name: 'pageTitle'
        widget: string