import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import copy from '@/assets/json/copy.json'
import useRepeatable from "../hooks/useRepeatable";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  console.log(useRepeatable)

  // const footerPromos = useRepeatable({ componentType: 'promo', copy: copy.footer, length: 3 })

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        {/* <Footer promos={footerPromos} /> */}
        </body>
    </html>
  );
}
